version: '3'
services:

  pellets-shiny:
    restart: always
    image: pellets:latest
    build: .
    container_name: pellets-shiny
    volumes:
      - ./:/app
    ports:
      - 3838:3838/tcp
    networks:
      - default
    environment:
      - GOOGLE_SHEETS_JSON_KEY=.secrets/earnest-vine-377812-6ae11f6184bc.json
      - ENV=docker
      
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx-shiny
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on: 
      - pellets-shiny
networks:
  default:
    driver: bridge