pkgs <- c(
    'shinyWidgets',
    'shinythemes',
    'shinydashboard',
    'shinyjs',
    'magrittr',
    'googlesheets4',
    'dplyr',
    'tibble',
    'leaflet',
    'stringr',
    'shiny',
    'tidygeocoder',
    'htmltools',
    'readr',
    'ggplot2',
    'shinycssloaders'
)
install.packages(pkgs)
